name: 打包应用并上传阿里云

on:
  push:
    branches:
      - Main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master

      - name: 安装node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.0.0

      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      # 上传阿里云
      - name: 发布到上传阿里云
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: '-avzr --delete'
          # 源目录
          SOURCE: './'
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: 'root'
          # 目标地址
          TARGET: '/home/admin/Bubble-Portfolio
